### ISSUE TITLE
Add block acceptance visualisation to utils

### ISSUE THREAD

**Issue by dglebowicz** [tscnlab/civibe_pupilprep#19]
From the analyse-block-acceptance notebook. Maybe add another utilities file that calculates various groupby's for analysis, so the visualisation functions are not too bloated?

**Comment by hsx1** [comment]
![Image](https://github.com/user-attachments/assets/2eac5920-5679-4309-a5c7-41c4318b766a)
awesome visualisation - hadn't seen it in the notebook before

**Comment by hsx1** [comment]
Is this the only things that's new?
I've written comments about the visualizations of original MAD and rolling MAD in slack.
